do
$setup_database$
begin
	create sequence if not exists hibernate_sequence;

	create table if not exists "user" (
	    use_cod bigint not null generated by default as identity,
	    use_username varchar not null,
	    use_email varchar not null,
		use_password varchar not null,
	    constraint user_use_cod_pkey primary key (use_cod),
	    constraint user_use_username_ukey unique (use_username),
	    constraint user_use_email_ukey unique (use_email)
	);

	create table if not exists task (
	    tas_cod bigint not null generated by default as identity,
	    tas_name varchar not null,
	    tas_created_at timestamp not null default now(),
	    tas_updated_at timestamp not null,
		tas_finished boolean not null default false,
		tas_use_cod bigint not null,
	    constraint task_tas_cod_pkey primary key (tas_cod),
	    constraint task_tas_use_cod_ukey foreign key (tas_use_cod) references "user"(use_cod)
	);

	if exists (select * from pg_catalog.pg_roles where rolname = 'todo_user') then
		reassign owned by todo_user to postgres;
		drop owned by todo_user;
		drop user todo_user;
	end if;

	create user todo_user with encrypted password 'wspsJJ@6h2/Tw293' 
		nosuperuser inherit nocreatedb nocreaterole noreplication valid until 'infinity';
 	grant connect on database todoapp to todo_user;
	grant usage on schema public to todo_user;
	grant select, insert, update, delete on all tables in schema public to todo_user;
	grant usage, select on all sequences in schema public to todo_user;
end
$setup_database$;
